# Generated by Django 4.2.4 on 2023-09-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialAPP', '0002_rename_specialapptable_specialapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialAPP',
            new_name='Special',
        ),
    ]
